#!/bin/python3

import os
import sys

#
# Complete the getTotalX function below.
#
def factor(x,a):
    #check if x is factor of all elements in a
    res=True
    for elem in a:
        if(x%elem!=0):
            res=False
            break
    return res

def inverse_factor(x,a):
    res=True
    for elem in a:
        if(elem%x!=0):
            res=False
            break
    return res


def getTotalX(a, b):
    #
    # Write your code here.
    #
    maxa=max(a)
    minb=min(b)
    start=maxa
    result=0
    while(start<=minb):
        if(factor(start,a)==True):
            break
        start+=maxa
    while(start<=minb):
        if(inverse_factor(start,b)==True):
            result+=1
        start+=maxa
    return result
            

if __name__ == '__main__':
    f = open(os.environ['OUTPUT_PATH'], 'w')

    nm = input().split()

    n = int(nm[0])

    m = int(nm[1])

    a = list(map(int, input().rstrip().split()))

    b = list(map(int, input().rstrip().split()))

    total = getTotalX(a, b)

    f.write(str(total) + '\n')

    f.close()
